name: taalim_ia
description: "TAALIM_IA - Application éducative CP1/CP2"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0 # Compatible avec le SDK Dart 3.7.0 de Flutter 3.29.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Rétrogradation requise pour la compatibilité avec le SDK Dart 3.7.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/content/
    - assets/icon/
    - assets/images/ # Déclaration générique pour toutes vos images 3D

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
